In [ ]:
import numpy as np
import pandas as pd
import pandas as pd
import os
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer 

In [ ]:
dataTrain = pd.read_csv('/content/drive/MyDrive/Học máy/preprocessing-data/csv/datatest.csv')

In [ ]:
file = open("/content/drive/MyDrive/Học máy/preprocessing-data/dictionary.txt",  encoding="utf8")
strs = file.read().split("\n")
strs=strs[:len(strs)-1]
keys=[]
for line in strs:
    s=line.split(" ")
    keys.append(s[0])

cv=CountVectorizer(vocabulary=keys)
word_count_vector=cv.fit_transform(dataTrain['content'])
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True) 
tfidf_transformer.fit(word_count_vector)

def computing_tfidf(s):
    input_s =[]
    input_s.append(s)
    count_vector=cv.transform(input_s) 
    tf_idf_vector=tfidf_transformer.transform(count_vector)
    values=tf_idf_vector.toarray().tolist()[0]
    dictionary = dict(zip(keys, values))
    return dictionary

In [ ]:
from gensim.models import KeyedVectors 
w2v = KeyedVectors.load_word2vec_format("vi/vi.vec")
vocab = w2v.wv.vocab #Danh sách các từ trong từ điển

<ipython-input-33-672233196ccc>:3: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  vocab = w2v.wv.vocab #Danh sách các từ trong từ điển


In [ ]:
X = np.zeros((dataTrain.shape[0],100))
for x in range(dataTrain.shape[0]):
    if x %100 ==0:
        print(x)
    dictX = computing_tfidf(dataTrain.iloc[x]['content'])
    words = dataTrain.iloc[x]['content'].split(" ")
    for word in words:
        if word in vocab and word in keys:
            X[x] += w2v[word]*dictX[word]

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18

In [ ]:
# save numpy array as csv file
from numpy import asarray
from numpy import savetxt

# save to csv file
savetxt('/content/drive/MyDrive/Học máy/preprocessing-data/word2vec/dataIntXTest.csv', X, delimiter=',')

In [ ]:
Y = dataTrain['lable']

In [ ]:
savetxt('/content/drive/MyDrive/Học máy/preprocessing-data/word2vec/dataIntYTest.csv', Y, delimiter=',')

In [ ]:
from numpy import loadtxt

X = loadtxt('/content/drive/MyDrive/Học máy/preprocessing-data/word2vec/dataIntXTrain.csv', delimiter=',')
Y = loadtxt('/content/drive/MyDrive/Học máy/preprocessing-data/word2vec/dataIntYTrain.csv', delimiter=',')

In [ ]:
#  làm tương tự để ra được Xtest, Ytest

In [ ]:
# from sklearn.svm import LinearSVC
# from sklearn.pipeline import make_pipeline
# from sklearn.preprocessing import StandardScaler
# from sklearn.datasets import make_classification
# clf = make_pipeline(StandardScaler(),LinearSVC(random_state=0, tol=1e-5))
# clf.fit(X, Y)

In [ ]:
from numpy import loadtxt
loadtxt('/content/drive/MyDrive/Học máy/preprocessing-data/word2vec/dataIntXTrain.csv', delimiter=',')

array([[ -0.17337701,   0.44102516,  -0.59886434, ...,  -0.86577302,
         -0.705952  ,  -0.43261562],
       [  0.67663032,  -0.15631613,  -2.27559092, ...,  -4.67029244,
         -0.78003657,  -3.1513128 ],
       [  1.16113371,  -0.05707228,  -3.11666214, ...,  -6.09308433,
         -0.5272067 ,  -3.39117023],
       ...,
       [ -1.09902865,   4.65849743,  -0.42249219, ...,  -6.37744897,
        -10.89173223,  -0.55052988],
       [  8.24298089,   6.70884637,  -1.06049629, ...,  -3.07991713,
          1.49550587,  -7.66872728],
       [ 10.40324971,  17.43008255,  -8.72542553, ...,  -9.19895273,
         -1.23947248,  -6.52831577]])

In [ ]:
X

array([[ -0.17337701,   0.44102516,  -0.59886434, ...,  -0.86577302,
         -0.705952  ,  -0.43261562],
       [  0.67663032,  -0.15631613,  -2.27559092, ...,  -4.67029244,
         -0.78003657,  -3.1513128 ],
       [  1.16113371,  -0.05707228,  -3.11666214, ...,  -6.09308433,
         -0.5272067 ,  -3.39117023],
       ...,
       [ -1.09902865,   4.65849743,  -0.42249219, ...,  -6.37744897,
        -10.89173223,  -0.55052988],
       [  8.24298089,   6.70884637,  -1.06049629, ...,  -3.07991713,
          1.49550587,  -7.66872728],
       [ 10.40324971,  17.43008255,  -8.72542553, ...,  -9.19895273,
         -1.23947248,  -6.52831577]])

In [ ]:
loadtxt('/content/drive/MyDrive/Học máy/preprocessing-data/word2vec/dataIntXTest.csv', delimiter=',')

array([[ -0.39094279,  11.56853605,   2.14841899, ..., -11.2161081 ,
        -16.11275834,  -5.28469989],
       [  1.22379772,   4.17840716,  -4.13654335, ...,  -2.21571638,
          0.34478771,  -6.14350989],
       [  0.55106026,   0.97034461,  -4.79770376, ...,  -3.12484702,
         -1.68741766,  -1.14646877],
       ...,
       [  4.25202273,   3.76211386,  -1.21353964, ...,  -1.22201033,
         -3.26653731,  -7.64459008],
       [  2.2227916 ,   2.543727  ,   0.7085698 , ...,   0.42600766,
          1.06869501,  -3.32309508],
       [  5.84109979,   8.99153285,  -3.42055182, ...,  -5.83945597,
          0.85473879,  -2.96701114]])

In [ ]:
X

array([[ -0.39094279,  11.56853605,   2.14841899, ..., -11.2161081 ,
        -16.11275834,  -5.28469989],
       [  1.22379772,   4.17840716,  -4.13654335, ...,  -2.21571638,
          0.34478771,  -6.14350989],
       [  0.55106026,   0.97034461,  -4.79770376, ...,  -3.12484702,
         -1.68741766,  -1.14646877],
       ...,
       [  4.25202273,   3.76211386,  -1.21353964, ...,  -1.22201033,
         -3.26653731,  -7.64459008],
       [  2.2227916 ,   2.543727  ,   0.7085698 , ...,   0.42600766,
          1.06869501,  -3.32309508],
       [  5.84109979,   8.99153285,  -3.42055182, ...,  -5.83945597,
          0.85473879,  -2.96701114]])